fresh_shop/cart/urls.py
from django.urls import path

from cart import views
from fresh_shop import urls

urlpatterns = [
    # 加入购物车
    path('add_cart/', views.add_cart, name='add_cart'),
    # 购物车的数量刷新
    path('cart_num/', views.cart_num, name='cart_num'),
    # 购物车
    path('cart/', views.cart, name='cart'),
    # 购物车计算价格
    path('cart_price/', views.cart_price, name='cart_price'),
    # 修改购物车中的数量/选择状态
    path('change_cart/', views.change_cart, name='change_cart'),
    # 删除购物车中的数据
    path('del_cart/<int:id>/', views.del_cart, name='del_cart'),
    path('change_select/', views.change_select, name='change_select'),
]

fresh_shop/fresh_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include,re_path
from django.views.static import serve

from fresh_shop.settings import MEDIA_URL, MEDIA_ROOT, STATICFILES_DIRS
from goods import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls','cart'),namespace='cart')),
    path('goods/', include(('goods.urls','goods'),namespace='goods')),
    path('order/', include(('order.urls','order'),namespace='order')),
    path('user/', include(('user.urls','user'),namespace='user')),
    # 首页路径
    path('', views.index),
    path(r'^media/(?P<path>.*)$',serve, {"document_root": MEDIA_ROOT}),
    path(r'^static/(?P<path>.*)$',serve, {"document_root": STATICFILES_DIRS[0]}),
]
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

fresh_shop/goods/urls.py
from django.urls import path, re_path

from fresh_shop import urls
from goods import views

urlpatterns = [
    # 首页
    path('index/', views.index, name='index'),
    # 详情
    path('detail/<int:id>/', views.detail, name='detail'),
    path('list/', views.list, name='list'),

]

fresh_shop/order/urls.py
from django.urls import path

from order import views
from fresh_shop import urls

urlpatterns = [
    # 结算功能
    path('place_order/', views.place_order, name='place_order'),
    # 创建订单
    path('order/', views.order, name='order'),
    # 全部订单
    path('user_order/', views.user_order, name='user_order'),
]

fresh_shop/user/urls.py
from django.urls import path

from fresh_shop import urls
from user import views

urlpatterns = [
    # 注册
    path('register/', views.register, name='register'),
    # 登录
    path('login/', views.login, name='login'),
    # 退出
    path('logout/', views.logout, name='logout'),
    # 收货地址
    path('user_site/', views.user_site, name='user_site'),
    # 个人中心
    path('user_info/', views.user_info, name='user_info'),

]

fresh_shop/cart/models.py
from django.db import models

# Create your models here.
from goods.models import Goods
from user.models import User


class ShoppingCart(models.Model):
    """
    购物车
    """
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
    nums = models.IntegerField(default=0, verbose_name='数量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
    is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'f_shopping_cart'

fresh_shop/cart/views.py
from django.http import JsonResponse
from django.shortcuts import render

from cart.models import ShoppingCart
from goods.models import Goods


def add_cart(request):
    if request.method == 'POST':
        # 接收商品id值和数量Num
        # 组装存储的商品格式：[goods_id, num , is_select]
        # 组装多个商品格式：[[goods_id, num , is_select, total_price],[goods_id, num , is_select]]
        goods_id = int(request.POST.get('goods_id'))
        goods_num = int(request.POST.get('goods_num'))
        # goods_shop_price = int(request.POST.get('goods_shop_price'))
        goods_list = [goods_id, goods_num, 1]
        session_goods = request.session.get('goods')
        if session_goods:
            # 1，添加重复的商品，则修改

            flag = True
            for se_goods in session_goods:
                if se_goods[0] == goods_id:
                    se_goods[1] += goods_num
                    flag = False
            if flag:
                # 2.添加的商品不存在购物车中，则新增
                session_goods.append(goods_list)
            request.session['goods'] = session_goods
            count = len(session_goods)

        else:
            # 第一次添加购物车，需组装购物车中商品格式为[[goods_id, num , is_select]]
            request.session['goods'] = [goods_list]
            count = 1
        return JsonResponse({'code': 200, 'msg': '请求成功', 'count': count})


def cart_num(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        count = len(session_goods) if session_goods else 0
        return JsonResponse({'code':200, 'msg':'请求成功', 'count':count})


def cart(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        # 组装返回格式[object1,object2]
        # object ===> [Goods object,  num, is_select, total_price]
        result = []
        if session_goods:

            for se_goods in session_goods:
                data = []
                # se_goods为[Goods object, is_select, num, total_price]
                goods = Goods.objects.filter(pk=se_goods[0]).first()
                total_price = goods.shop_price * se_goods[1]
                data = [goods, se_goods[1], se_goods[2], total_price]
                result.append(data)
        return render(request, 'cart.html', {'result':result})


def cart_price(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        # 总的商品件数
        all_total = len(session_goods) if session_goods else 0
        all_price = 0
        is_select_num = 0
        for se_goods in  session_goods:
            if se_goods[2]:
                total = 0
                goods = Goods.objects.filter(pk=se_goods[0]).first()
                all_price += goods.shop_price * se_goods[1]
                is_select_num += 1

        return JsonResponse({'code':200, 'msg': '请求成功', 'all_total': all_total, 'all_price': all_price,'is_select_num':is_select_num})


def change_cart(request):
    if request.method == 'POST':
        # 修改商品的数量和选择状态
        # 其实就是修改session中商品信息, 结果为[goods_id,num,is_select]
        # 1.获取商品id值和(数量或者选择状态)
        goods_id = int(request.POST.get('goods_id'))
        goods_num = request.POST.get('goods_num')
        goods_select = request.POST.get('goods_select')
        # 修改session中的数据
        session_goods = request.session.get('goods')
        for se_goods in session_goods:
            if se_goods[0] == goods_id:
                se_goods[1] = int(goods_num) if goods_num else se_goods[1]
                se_goods[2] = int(goods_select) if goods_select else se_goods[2]
        request.session['goods'] = session_goods
        return JsonResponse({'code':200, 'msg':'请求成功'})


def del_cart(request, id):
    if request.method == 'POST':
        # 通过传入的商品id值去session中查找，查找到则删除数据
        # goods_id = int(request.POST.get('goods_id'))
        session_goods = request.session.get('goods')
        for se_goods in session_goods:
            if se_goods[0] == id:
               session_goods.remove(se_goods)
               break
        request.session['goods'] = session_goods
        user_id = request.session.get('user_id')
        if user_id:
            # 删除数据库
            ShoppingCart.objects.filter(goods_id=id, user_id=user_id).delete()
        return JsonResponse({'code':200, 'msg': '请求成功'})


def change_select(request):
    if request.method == 'POST':
        goods_id = request.POST.get('goods_id')
        session_goods = request.session.get('goods')
        for se_goods in session_goods:
            if se_goods[0] == int(goods_id):
                if se_goods[2] == 0:
                    se_goods[1] -= 1
                    se_goods[2] = 1
                else:
                    se_goods[1] += 1
                    se_goods[2] = 0
                request.session['goods'] = session_goods
        return JsonResponse({'code':200, 'msg':'请求成功'})

fresh_shop/templates/base_main.html
{% extends 'base.html' %}
    {% block css %}
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
    {% endblock %}

    {% block js1 %}
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    {% endblock %}

    {% block header %}
        <div class="header_con">
                <div class="header">
                    <div class="welcome fl">欢迎来到天天生鲜!</div>
                    <div class="fr">
                        <div class="login_info fl" {% if user.id %} style="display:block" {% endif %}>
                            欢迎您：<em>{{ user.username }}</em>
                            <span>|</span>
                            <a href="{% url 'user:logout' %}">退出</a>
                        </div>
                        <div class="login_btn fl" {% if user.id %}style="display:none"{% endif %}>
                            <a href="{% url 'user:login' %}">登录</a>
                            <span>|</span>
                            <a href="{% url 'user:register' %}">注册</a>
                        </div>
                        <div class="user_link fl">
                            <span>|</span>
                            <a href="{% url 'user:user_info' %}">用户中心</a>
                            <span>|</span>
                            <a href="{% url 'cart:cart' %}">我的购物车</a>
                            <span>|</span>
                            <a href="{% url 'order:user_order' %}">我的订单</a>
                        </div>
                    </div>
                </div>
            </div>
    {% endblock %}

    {% block search %}
<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<a href="{% url 'goods:list' %}?page=1"><input type="button" class="input_btn fr" name="" value="搜索"></a>
		</div>
        <script>
            function search(){
            var name = $('.search_con .input_text').val()
            if(not name){

                aler('请输入您要搜索的商品名！')
            }else{
                $.ajax({
                    url:''
                })

            }

            }

        </script>
		<div class="guest_cart fr">
			<a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
    <script>
        $.get('/cart/cart_num/', function(data){
        if(data.code == '200'){
        $('#show_count').text(data.count)
        }
        })

    </script>
	</div>
    {% endblock %}
{% block footer %}
<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{% endblock %}

fresh_shop/templates/base_user.html
<ul>
	<li><a href="{% url 'user:user_info' %}" {% if activate == 'info' %}class="active"{% endif %}>· 个人信息</a></li>
	<li><a href="{% url 'order:user_order' %}"{% if activate == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
	<li><a href="{% url 'user:user_site' %}"{% if activate == 'site' %}class="active"{% endif %}>· 收货地址</a></li>
</ul>

fresh_shop/templates/index.html
{% extends 'base_main.html' %}

{% block title %}
	天天生鲜-首页
{% endblock %}

{% block js1 %}
{{ block.super }}
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/slide.js"></script>
{% endblock %}
{% block content %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="{% url 'goods:list' %}?page=1" class="fruit">新鲜水果</a></li>
			<li><a href="{% url 'goods:list' %}?page=2" class="seafood">海鲜水产</a></li>
			<li><a href="{% url 'goods:list' %}?page=3" class="meet">猪牛羊肉</a></li>
			<li><a href="{% url 'goods:list' %}?page=4" class="egg">禽类蛋品</a></li>
			<li><a href="{% url 'goods:list' %}?page=5" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="{% url 'goods:list' %}?page=6" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg"></a>
			<a href="#"><img src="/static/images/adv02.jpg"></a>
		</div>
	</div>
{% for data in result %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">
				{% for type in category_type %}
					{% if type.0 == data.0.category_type %}
						{{ type.1 }}
					{% endif %}
				{% endfor %}
			</h3>
			<div class="subtitle fl">
			</div>
			<a href="{% url 'goods:list' %}?page={{ data.0.category_type }}" class="goods_more fr" id="">查看更多 ></a>
		</div>
		<div class="goods_con clearfix">
			<div class="goods_banner fl" ><img src="/media/{{ data.0.category_front_image }}"></div>
			<ul class="goods_list fl">
				{% for i in data.1 %}
				<li>
					<h4><a href="{% url 'goods:detail' i.id %}">{{ i.name }}</a></h4>
					<a href="{% url 'goods:detail' i.id %}"><img src="/media/{{ i.goods_front_image }}"></a>
					<div class="prize">{{ i.shop_price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
{% endfor %}
{% endblock %}
{% block js2 %}
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/slideshow.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock %}

fresh_shop/templates/login.html
{% extends 'base_main.html' %}
{% block title %}
天天生鲜
{% endblock %}
{% block header %}
{% endblock %}

{% block search %}
{% endblock %}
{% block content %}
<body>
	<div class="login_top clearfix">
		<a href="{% url 'goods:index' %}" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input" >
					<form method="post">
						{% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error" style="display:block">{{ errors.username }}</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error" style="display:block">{{ errors.pwd }}</div>
						<input type="submit" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

</body>
{% endblock %}

fresh_shop/templates/place_order.html
{% extends 'base_main.html' %}
{% block title %}
	天天生鲜-提交订单
{% endblock %}
{% block search %}

	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;提交订单</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<a href="{% url 'goods:list' %}page=1"><input type="button" class="input_btn fr" name="" value="搜索"></a>
		</div>		
	</div>
{% endblock %}
{% block content %}
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			{% for address in user_address %}
			<dd>
				<input type="radio" name="address_radio" value="{{ address.id }}">
				{{ address.address }}({{ address.name }} 收)
				{{ address.signer_mobile }}
			</dd>
			{% endfor %}
		</dl>
		<a href="{% url 'user:user_site' %}" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>
		</ul>
		{% for cart in carts %}
		<ul class="goods_list_td clearfix">
			<li class="col01">{{ forloop.counter }}</li>
			<li class="col02"><img src="/media/{{ cart.goods.goods_front_image }}"></li>
			<li class="col03">{{ cart.goods.name }}</li>
			<li class="col04">500g</li>
			<li class="col05">{{ cart.goods.shop_price }}</li>
			<li class="col06">{{ cart.nums }}</li>
			<li class="col07">{{ cart.goods_price }}</li>
		</ul>
		{% endfor %}

	</div>
	<h3 class="common_title">总金额结算</h3>
	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ num }}</em>件商品，总金额<b>{{ total_price }}</b></div>
			<div class="transit">运费：<b>10元</b></div>
			<div class="total_pay">实付款：<b>{{ total_price | add:'10' }}</b></div>
		</div>
	</div>
	<div class="order_submit clearfix">
		<a href="javascript:;" id="order_btn">提交订单</a>
	</div>	
{% endblock %}


{% block footer %}
{{ block.super }}
	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>
{% endblock %}
{% block js2 %}
	{% csrf_token %}
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
		$('#order_btn').click(function() {
			localStorage.setItem('order_finish',2);
			<!--判断是否选择收货地址-->
			var address_radio = $('input[name="address_radio"]')
			for(var i=0; i<address_radio.length; i++){
				if(address_radio[i].checked == true){
					var ad_id = address_radio[i].value;
				}

			}
			if(ad_id){
				<!--创建订单-->
				var csrf = $('input[name="csrfmiddlewaretoken"]').val()
				$.ajax({
				url: '/order/order/',
				type: 'POST',
				data: {'ad_id': ad_id},
				dataType: 'json',
				headers:{'X-CSRFToken':csrf},
				success:function(data){
				$('.popup p').text('提交订单成功')
				$('.popup_con').fadeIn('fast', function() {
					setTimeout(function(){
						$('.popup_con').fadeOut('fast',function(){
							window.location.href = '/goods/index/';
						});
					},3000)
				});
				},
				error:function(data){
				$('.popup p').text('提交订单失败')
				}
				})
			}
			else{
				<!--修改弹窗的信息“提交订单失败(请选择收货地址)”-->
				$('.popup p').text('提交订单失败(请选择收货地址)')
				$('.popup_con').fadeIn('fast', function() {

				setTimeout(function(){
					$('.popup_con').fadeOut('fast',function(){
						<!--window.location.href = 'index.html';-->
					});
				},3000)
				});
			}
		});
	</script>
{% endblock %}

fresh_shop/templates/register.html
{% extends 'base_main.html' %}
{% block title %}
用户注册
{% endblock %}
{% block js1 %}
{% endblock %}
	{{ block.super }}
	<script type="text/javascript" src="/static/js/register.js"></script>
{% block header %}
{% endblock %}

{% block search %}
{% endblock %}
{% block content %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="" method="post">
				{% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip" style="display:block">{{ errors.user_name }}</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip" style="display:block">{{ errors.pwd }}</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip" style="display:block">{{ errors.cpwd }}</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip" style="display:block">{{ errors.email }}</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2" style="display:block">{{ errors.allow }}</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>

{% endblock %}

fresh_shop/templates/user_center_info.html
{% extends 'base_main.html' %}
{% block title %}

天天生鲜-用户中心
{% endblock  %}

	{% block search %}

	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<a href="{% url 'goods:list' %}page=1"><input type="button" class="input_btn fr" name="" value="搜索"></a>
		</div>		
	</div>
{% endblock %}
{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			{% include 'base_user.html' %}
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
							<!--<li><span>联系方式：</span>18210569700</li>-->
							<!--<li><span>联系地址：</span>北京市昌平区</li>			-->
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
				{% for good in all_goods %}
				<li>
					<a href="detail.html"><img src="/media/{{ good.goods_front_image}}"></a>
					<h4><a href="detail.html">{{ good.name }}</a></h4>
					<div class="operate">
						<span class="prize">{{ good.shop_price }}</span>
						<span class="unit">{{ good.shop_price }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				{% endfor %}
			</ul>
		</div>
		</div>
	</div>
{% endblock %}

fresh_shop/templates/user_center_order.html
{% extends 'base_main.html' %}
{% block title %}
	天天生鲜-用户中心
{% endblock %}
{% block search %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<a href="{% url 'goods:list' %}?page=1"><input type="button" class="input_btn fr" name="" value="搜索"></a>
		</div>
	</div>
{% endblock %}
{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			{% include 'base_user.html' %}
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
			{% for order in orders %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.add_time }}</li>
					<li class="col02" style="width:55%">订单号:{{ order.order_sn }}</li>
					<li class="col02 stress">待支付:{% for s in status %}
										{% ifequal s.o order.pay_status %}
										{{ s.1 }}
										{% endifequal %}
									{% endfor %}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>

						<tr>
							<td width="55%">
								{% for order_goods in order.goods.all %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/media/{{ order_goods.goods.goods_front_image }}"></li>
									<li class="col02">{{ order_goods.goods.name }}<em>{{ order_goods.goods.shop_price }}</em></li>
									<li class="col03">{{ order_goods.goods_nums }}</li>
									<li class="col04">{{ order_goods.goods.shop_price }}</li>

								</ul>
								{% endfor %}
							</td>
							<td width="15%">{{ order.order_mount }}元</td>
							<td width="15%">
								{% for s in status %}
										{% ifequal s.0 order.pay_status %}
										{{ s.1 }}
										{% endifequal %}
								{% endfor %}
							</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
				{% endfor %}
				<div class="pagenation">
					{% if orders.has_previous %}
						<a href="{% url 'order:user_order' %}?page={{ orders.previous_page_number }}">上一页 </a>
					{% endif %}
					{% for i in orders.paginator.page_range %}
						<a href="{% url 'order:user_order' %}?page={{ i }}"> {{ i }}</a>
					{% endfor %}
					{% if orders.has_next %}
						<a href="{% url 'order:user_order' %}?page={{ orders.next_page_number }}">下一页 </a>
					{% endif %}
				</div>
		</div>
	</div>

{% endblock %}