myblog/article/urls.py
from django.urls import path

from article import views

urlpatterns = [
    path('article/', views.article, name='article'),
    path('category/', views.category, name='category'),
    path('add_article/', views.add_article, name='add_article'),
    path('change_article/<int:id>/', views.change_article, name='change_article'),
    path('del_article/<int:id>/', views.del_article, name='del_article'),
    path('update_article/', views.update_article,name='update_article'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('article/', include(('article.urls', 'article'), namespace='article')),
]

myblog/user/urls.py
from django.urls import path

from user import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('index/', views.index, name='index'),
    path('del_user/<int:id>/', views.del_user, name='del_user')

]

myblog/article/models.py
from django.db import models


class Article(models.Model):

    a_title = models.CharField(max_length=20)
    a_content = models.CharField(max_length=1500)
    a_pre = models.CharField(max_length=20)
    a_time = models.DateField(auto_now_add=True)
    a_category = models.IntegerField()

    class Meta:
        db_table = 'article'


class Category(models.Model):
    c_name = models.CharField(max_length=20)
    c_pre = models.CharField(max_length=20)

    class Meta:
        db_table = 'category'


class Bei(models.Model):
    b_name = models.CharField(max_length=20)
    b_pre = models.CharField(max_length=20)
    b_b = models.IntegerField()

    class Meta:
        db_table = 'bei'

myblog/user/models.py
from django.db import models


class User(models.Model):
    u_name = models.CharField(max_length=10, verbose_name='姓名')
    u_password = models.CharField(max_length=150, verbose_name='密码')
    # u_email = models.EmailField(verbose_name='邮箱')

    class Meta:
        db_table = 'user'

myblog/user/forms.py
from django import forms

from user.models import User


class StuForm(forms.Form):
    username = forms.CharField(max_length=10,min_length=2,required=True,
                               error_messages={'required':'姓名是必填值',
                                                'min_length': '不能少于2个字符',
                                                'max_length': '不能超过10个字符'})

    password1 = forms.CharField(required=True, error_messages={'required': '密码必填'
                                                             })
    password2 = forms.CharField(required=True, error_messages={'required': '密码必填'})

    def clean_username(self):
        username = self.cleaned_data.get('username')
        user = User.objects.filter(u_username=username).first()
        if user:
            raise forms.ValidationError('你输入的用户名已经注册过了')
        return self.cleaned_data['username']

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
            raise forms.ValidationError('您输入的密码不一致')
        return self.cleaned_data

myblog/article/views.py
from django.core.paginator import Paginator
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from article.models import Article

from user.models import User


def article(request):
    if request.method == 'GET':
        articles = []
        article = Article.objects.all()
        num = len(article)
        username = request.session.get('username')
        user = User.objects.filter(u_name=username).first()
        for article1 in article:
            articles.append(article1)
            result = [user, articles, num]
        page = request.GET.get('page',1)
        pg = Paginator(article, 3)
        article = pg.page(page)

        # [user, [article1,....,articlen]]
        return render(request, 'article.html',{'article': article,'user':user, 'num':num})


def category(request):
    if request.method == 'GET':
        return render(request,'category.html')


def add_article(request):
    if request.method == 'GET':
        return render(request,'add-article.html')
    if request.method == 'POST':
        articles = []
        title = request.POST.get('title')
        content = request.POST.get('content')
        category = request.POST.get('category')
        tags = int(request.POST.get('tags'))
        titlepic = request.POST.get('titlepic')
        article = Article.objects.create(a_title=title,a_content=content,a_pre=category,a_category=tags)
        username = request.session.get('username')
        if not username:
            return HttpResponseRedirect(reverse('article:article'))
        articles.append(article)
        result = [username, articles]
        # request.session['article'] = article
        return render(request, 'add-article.html',{'result':result})


def change_article(request, id):
    if request.method == 'POST':
        articles = Article.objects.filter(id=id).first()
        return JsonResponse({'code':200, 'msg':'请求成功'})





def del_article(request, id):
    if request.method == 'POST':
        Article.objects.filter(id=id).delete()
        return JsonResponse({'code':200, 'msg':'请求成功'})


def update_article(request):
    if request.method == 'GET':
        return render(request, 'update-article.html')

myblog/user/views.py
from django.contrib.auth.hashers import make_password, check_password
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect, JsonResponse
from user.models import User


def register(request):
    if request.method == 'GET':
        return  render(request, 'register.html')
    if request.method == 'POST':
        username = request.POST.get('username')
        password1= request.POST.get('password1')
        password2= request.POST.get('password2')
        if username and password2 and password1:
            user = User.objects.filter(u_name=username).first()
            if user:
                msg = '您注册的用户名已经存在'
                return render(request, 'register.html', {'msg': msg})
            if password1 != password2:
                msg = '您输入的密码不一致'
                return render(request, 'register.html', {'msg': msg})
            password = make_password(password1)
            User.objects.create(u_name=username, u_password=password)
            return HttpResponseRedirect(reverse('user:login'))
        msg = '您的用户名、密码或确认密码不能为空！'
        return render(request, 'register.html', {'msg':msg})


def login(request):
    if request.method == 'GET':
        return render(request, 'login.html')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        if username and password:
            user = User.objects.filter(u_name=username).first()
            if not user:
                msg = '您输入的用户名不存在'
                return render(request, 'login.html', {'msg': msg})

            if not check_password(password, user.u_password):
                msg = '您输入的密码有误'
                return render(request, 'login.html', {'msg':msg})
            request.session['user_id'] = user.id
            return HttpResponseRedirect(reverse('article:article'))
        msg = '您输入的用户名或者密码不能为空'
        return render(request, 'login.html',{'msg':msg})


def index(request):
    if request.method == 'GET':
        return render(request, 'article.html')


def del_user(request,id):
    if request.method == 'POST':
        user_id = request.method.get('user_id')
        if user_id == id:
            request.session['user_id'].delete()
            User.objects.filter(pk=id).delete()
            return JsonResponse({'code':200, 'msg':'请求成功'})

myblog/templates/add-category.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>无标题文档</title>
</head>

<body>
</body>
</html>

myblog/templates/article.html
{% extends 'base_main.html' %}
{% block title %}
文章 - 异清轩博客管理系统
{% endblock %}
{% block css %}
{{ block.super }}
{% endblock %}
{% block js1 %}
{{ block.super }}
{% endblock %}
<body class="user-select">
<section class="container-fluid">
 {% block header %}
  {{ block.super }}
  {% endblock %}
  <div class="row">
    {% block aside %}
    {{ block.super }}
    {% endblock %}
    {% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <form action="" method="post" >
        {% csrf_token %}
        <h1 class="page-header">操作</h1>
        <ol class="breadcrumb">
          <li><a href="{% url 'article:add_article' %}">增加文章</a></li>
        </ol>
        <h1 class="page-header">管理 <span class="badge">{{ num }}</span></h1>
        <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th><span class="glyphicon glyphicon-th-large"></span> <span class="visible-lg">选择</span></th>
                <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">标题</span></th>
                <th><span class="glyphicon glyphicon-list"></span> <span class="visible-lg">栏目</span></th>
                <th class="hidden-sm"><span class="glyphicon glyphicon-tag"></span> <span class="visible-lg">标签</span></th>
                <!--<th class="hidden-sm"><span class="glyphicon glyphicon-comment"></span> <span class="visible-lg">评论</span></th>-->
                <th><span class="glyphicon glyphicon-time"></span> <span class="visible-lg">日期</span></th>
                <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
              </tr>
            </thead>
            <tbody>
              {% for a in article %}
              <tr id="article_{{ a.id }}">
                <td>{{ a.id }}</td>
                <td class="article-title">{{ a.a_title }}</td>
                <td>{{ a.a_category }}</td>
                <td class="hidden-sm">{{ a.a_pre }}</td>
                <!--<td class="hidden-sm">0</td>-->
                <td>{{ a.a_time }}</td>
                <td><a href="{% url 'article:update_article' %}">修改</a> <a  rel="6" onclick="del_article({{ a.id }})">删除</a></td>
              </tr>
              {% endfor %}

            </tbody>
          </table>
        </div>
        <footer class="message_footer">
          <nav>
            <div class="btn-toolbar operation" role="toolbar">
              <!--<div class="btn-group" role="group"> <a class="btn btn-default" onClick="select()">全选</a> <a class="btn btn-default" onClick="reverse()">反选</a> <a class="btn btn-default" onClick="noselect()">不选</a> </div>-->
              <!--<div class="btn-group" role="group">-->
                <!--<button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="删除全部选中" name="checkbox_delete">删除</button>-->
              <!--</div>-->
            </div>
            <ul class="pagination pagenav">
              {% if article.has_previous %}
              <li class="disabled"><a aria-label="Previous" href="{% url 'article:article' %}?page={{ article.previous_page_number }}"> <span aria-hidden="true">&laquo;</span> </a> </li>
              {% endif %}
              {% for i in article.paginator.page_range %}
              <li class=""><a href="{% url 'article:article' %}?page={{ i }}">{{ i }}</a></li>
              {% endfor %}
              {% if article.has_next %}
              <li><a href="{% url 'article:article' %}?page={{ article.next_page_number }}" aria-label="Next"> <span aria-hidden="true">&raquo;</span> </a> </li>
              {% endif %}

            </ul>
          </nav>
        </footer>
      </form>
    </div>
  </div>
</section>
<!--个人信息模态框-->
<div class="modal fade" id="seeUserInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <form action="" method="post">
      {% csrf_token %}
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" >个人信息</h4>
        </div>
        <div class="modal-body">
          <table class="table" style="margin-bottom:0px;">
            <thead>
              <tr> </tr>
            </thead>
            <tbody>
              <tr>
                <td wdith="20%">姓名:</td>
                <td width="80%"><input type="text" value="王雨" class="form-control" name="truename" maxlength="10" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">用户名:</td>
                <td width="80%"><input type="text" value="admin" class="form-control" name="username" maxlength="10" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">电话:</td>
                <td width="80%"><input type="text" value="18538078281" class="form-control" name="usertel" maxlength="13" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">旧密码:</td>
                <td width="80%"><input type="password" class="form-control" name="old_password" maxlength="18" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">新密码:</td>
                <td width="80%"><input type="password" class="form-control" name="password" maxlength="18" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">确认密码:</td>
                <td width="80%"><input type="password" class="form-control" name="new_password" maxlength="18" autocomplete="off" /></td>
              </tr>
            </tbody>
            <tfoot>
              <tr></tr>
            </tfoot>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
          <button type="submit" class="btn btn-primary">提交</button>
        </div>
      </div>
    </form>
  </div>
</div>
<!--个人登录记录模态框-->
<div class="modal fade" id="seeUserLoginlog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" >登录记录</h4>
      </div>
      <div class="modal-body">
        <table class="table" style="margin-bottom:0px;">
          <thead>
            <tr>
              <th>登录IP</th>
              <th>登录时间</th>
              <th>状态</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>::1:55570</td>
              <td>2016-01-08 15:50:28</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:64377</td>
              <td>2016-01-08 10:27:44</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:64027</td>
              <td>2016-01-08 10:19:25</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:57081</td>
              <td>2016-01-06 10:35:12</td>
              <td>成功</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">朕已阅</button>
      </div>
    </div>
  </div>
</div>
<!--微信二维码模态框-->
<div class="modal fade user-select" id="WeChat" tabindex="-1" role="dialog" aria-labelledby="WeChatModalLabel">
  <div class="modal-dialog" role="document" style="margin-top:120px;max-width:280px;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="WeChatModalLabel" style="cursor:default;">微信扫一扫</h4>
      </div>
      <div class="modal-body" style="text-align:center"> <img src="/static/images/weixin.jpg" alt="" style="cursor:pointer"/> </div>
    </div>
  </div>
</div>
<!--提示模态框-->
<div class="modal fade user-select" id="areDeveloping" tabindex="-1" role="dialog" aria-labelledby="areDevelopingModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="areDevelopingModalLabel" style="cursor:default;">该功能正在日以继夜的开发中…</h4>
      </div>
      <div class="modal-body"> <img src="/static/images/baoman/baoman_01.gif" alt="深思熟虑" />
        <p style="padding:15px 15px 15px 100px; position:absolute; top:15px; cursor:default;">很抱歉，程序猿正在日以继夜的开发此功能，本程序将会在以后的版本中持续完善！</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">朕已阅</button>
      </div>
    </div>
  </div>
</div>
<!--右键菜单列表-->
<div id="rightClickMenu">
  <ul class="list-group rightClickMenuList">
    <li class="list-group-item disabled">欢迎访问异清轩博客</li>
    <li class="list-group-item"><span>IP：</span>172.16.10.129</li>
    <li class="list-group-item"><span>地址：</span>河南省郑州市</li>
    <li class="list-group-item"><span>系统：</span>Windows10 </li>
    <li class="list-group-item"><span>浏览器：</span>Chrome47</li>
  </ul>
</div>
{% endblock %}
{% block js2 %}
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/admin-scripts.js"></script>
<script>
<!--//是否确认删除-->
<!--$(function(){-->
	<!--$("#main table tbody tr td a").click(function(){-->
		<!--var name = $(this);-->
		<!--var id = name.attr("rel"); //对应id-->
		<!--if (event.srcElement.outerText == "删除")-->
		<!--{-->
			<!--if(window.confirm("此操作不可逆，是否确认？"))-->
			<!--{-->
				<!--$.ajax({-->
					<!--type: "POST",-->
					<!--url: "/Article/delete",-->
					<!--data: "id=" + id,-->
					<!--cache: false, //不缓存此页面-->
					<!--success: function (data) {-->
						<!--window.location.reload();-->
					<!--}-->
				<!--});-->
			<!--};-->
		<!--};-->
	<!--});-->
<!--});-->
<!--{% csrf_token %}-->
function del_article(id){
  var csrf = $('input[name="csrfmiddlewaretoken"]').val()
  $.ajax({
    url:'/article/del_article/' + id + '/',
    type:'POST',
    data:{'id':id},
    dataType:'json',
    headers:{'X-CSRFToken':csrf},
    successs:function(data){
      $('#article_' + id).remove()
    },
    error:function(data){
      console.log('123456')
      alert('请求失败')
    }
  })

}


</script>
{% endblock %}

myblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
      {% block media %}
           {% endblock %}
       <title>
           {% block title %}
           {% endblock %}


       </title>

    {% block css %}
    {% endblock %}

    {% block js1 %}
    {% endblock %}

</head>
<body class="user-select">

{% block header %}
{% endblock %}

{% block aside %}
{% endblock %}

{% block content %}
{% endblock %}

{% block js2 %}
{% endblock %}
</body>
</html>

myblog/templates/base_main.html
{% extends 'base.html' %}
{% block media %}
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/css/font-awesome.min.css">
<link rel="apple-touch-icon-precomposed" href="/static/images/icon/icon.png">
<link rel="shortcut icon" href="/static/images/icon/favicon.ico">
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
{% endblock %}
{% block js1 %}
  <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js" type="text/javascript"></script>
  <script src="/static/js/html5shiv.min.js" type="text/javascript"></script>
  <script src="/static/js/respond.min.js" type="text/javascript"></script>
  <script src="/static/js/selectivizr-min.js" type="text/javascript"></script>
{% endblock %}
{% block header %}
<header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">切换导航</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="/">YlsatCMS</a> </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <!--<li><a href="">消息 <span class="badge">1</span></a></li>-->
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="display:block">{{ user.u_name}}</a>
              <li><a href="{% url 'user:login' %}">登录</a></li>
              <ul class="dropdown-menu dropdown-menu-left">
                <!--<li><a title="查看或修改个人信息" data-toggle="modal" data-target="#seeUserInfo">个人信息</a></li>-->
                <!--<li><a title="查看您的登录记录" data-toggle="modal" data-target="#seeUserLoginlog">登录记录</a></li>-->
              </ul>
            </li>
            <li><a href="{% url 'article:article' %}" onClick="del_user({{ user.id }})">退出登录</a></li>
            <script>
            {% csrf_token %}
            function del_user(id){
              var csrf = $('input[name="csrfmiddlewaretoken"]').val()
              $.ajax({
                url:'/user/del_user/' + id + '/',
                type:'POST',
                data:{'user_id':id},
                headers:{'X-CSRFToken':csrf},
                dataType:'json',
                success:function(data){
                  console.log(data)
                },
                error:function(data){
                  console.log(data)
                  alert('请求失败')
                }
              })
              }
            </script>
            <!--<li><a data-toggle="modal" data-target="#WeChat">帮助</a></li>-->
          </ul>
          <form action="" method="post" class="navbar-form navbar-right" role="search">
            {% csrf_token %}
            <div class="input-group">
              <input type="text" class="form-control" autocomplete="off" placeholder="键入关键字搜索" maxlength="15">
              <span class="input-group-btn">
              <button class="btn btn-default" type="submit">搜索</button>
              </span> </div>
          </form>
        </div>
      </div>
    </nav>
  </header>
{% endblock %}
{% block aside %}
<aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
      <ul class="nav nav-sidebar">
        <!--<li class="active"><a href="index.html">报告</a></li>-->
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'article:article' %}">文章</a></li>
        <!--<li><a href="notice.html">公告</a></li>-->
        <!--<li><a href="comment.html">评论</a></li>-->
        <!--<li><a data-toggle="tooltip" data-placement="bottom" title="网站暂无留言功能">留言</a></li>-->
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'article:category' %}">栏目</a></li>
        <!--<li><a class="dropdown-toggle" id="otherMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">其他</a>-->
          <ul class="dropdown-menu" aria-labelledby="otherMenu">
            <!--<li><a href="flink.html">友情链接</a></li>-->
            <!--<li><a data-toggle="modal" data-target="#areDeveloping">访问记录</a></li>-->
          </ul>
        </li>
      </ul>
      <ul class="nav nav-sidebar">
        <!--<li><a class="dropdown-toggle" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">用户</a>-->
          <ul class="dropdown-menu" aria-labelledby="userMenu">
            <!--<li><a data-toggle="modal" data-target="#areDeveloping">管理用户组</a></li>-->
            <!--<li><a href="manage-user.html">管理用户</a></li>-->
            <li role="separator" class="divider"></li>
            <!--<li><a href="loginlog.html">管理登录日志</a></li>-->
          </ul>
        </li>
        <!--<li><a class="dropdown-toggle" id="settingMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">设置</a>-->
          <ul class="dropdown-menu" aria-labelledby="settingMenu">
            <!--<li><a href="setting.html">基本设置</a></li>-->
            <!--<li><a href="readset.html">阅读设置</a></li>-->
            <li role="separator" class="divider"></li>
            <!--<li><a data-toggle="modal" data-target="#areDeveloping">安全配置</a></li>-->
            <li role="separator" class="divider"></li>
            <!--<li class="disabled"><a>扩展菜单</a></li>-->
          </ul>
        </li>
      </ul>
    </aside>
{% endblock %}
{% block js2 %}
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
{% endblock %}

myblog/templates/login.html
{% extends 'base_main2.html' %}
{% block title %}
  异清轩博客管理系统
{% endblock %}
<body class="user-select">
{% block content %}
<div class="container">
  <div class="siteIcon"><img src="/static/images/icon/icon.png" alt="" data-toggle="tooltip" data-placement="top" title="欢迎使用异清轩博客管理系统" draggable="false" /></div>
  <form action="" method="post" autocomplete="off" class="form-signin">
    {% csrf_token %}
    <h2 class="form-signin-heading">管理员登录  <a href="{% url 'user:register' %}" style="color:red;margin-left:80px">注册</a></h2>
    <label for="userName" class="sr-only">用户名</label>
    <input type="text" id="userName" name="username" class="form-control" placeholder="请输入用户名" required autofocus autocomplete="off" maxlength="10">
    <label for="userPwd" class="sr-only">密码</label>
    <input type="password" id="userPwd" name="password"  style="margin-top:15px" class="form-control" placeholder="请输入密码" required autocomplete="off" maxlength="18">
    <!--<label for="userPwd" class="sr-only">密码</label>-->
    <!--<input type="password" id="userPwd1" name="password2" class="form-control" placeholder="请输入密码" required autocomplete="off" maxlength="18">-->
    <a href=""><button class="btn btn-lg btn-primary btn-block" type="submit" id="signinSubmit">登录</button></a>
    <font style="color:red;font-size:20px;">{{ msg }}</font>

  </form>
  <!--<div class="footer">-->
    <!--&lt;!&ndash;<p><a href="index.html" data-toggle="tooltip" data-placement="left" title="不知道自己在哪?">回到后台 →</a></p>&ndash;&gt;-->
  <!--</div>-->
</div>
{% endblock %}
{% block js2 %}
{{ block.super }}
<script src="/static/js/bootstrap.min.js"></script>
<script>
$('[data-toggle="tooltip"]').tooltip();
window.oncontextmenu = function(){
	//return false;
};
$('.siteIcon img').click(function(){
	window.location.reload();
});
$('#signinSubmit').click(function(){
	if($('#userName').val() === ''){
		$(this).text('用户名不能为空');
	}else if($('#userPwd').val() === ''){
		$(this).text('密码不能为空');
	}else{
		$(this).text('请稍后...');
	}
});
</script>
{% endblock %}

myblog/templates/register.html
{% extends 'base_main2.html' %}
{% block title %}
  异清轩博客管理系统
{% endblock %}
<body class="user-select">
{% block content %}
<div class="container">
  <div class="siteIcon"><img src="/static/images/icon/icon.png" alt="" data-toggle="tooltip" data-placement="top" title="欢迎使用异清轩博客管理系统" draggable="false" /></div>
  <form action="" method="post" autocomplete="off" class="form-signin">
    {% csrf_token %}
    <h2 class="form-signin-heading">管理员注册 <a href="{% url 'user:login' %}" style="color:red;margin-left:80px">登录</a></h2>
    <label for="userName" class="sr-only">用户名</label>
    <input type="text" id="userName" name="username" class="form-control" placeholder="请输入用户名" required autofocus autocomplete="off" maxlength="10">
    <label for="userPwd" class="sr-only" >密码</label>
    <input type="password" id="userPwd" name="password1" style="margin-top:15px" class="form-control" placeholder="请输入密码" required autocomplete="off" maxlength="18">
    <label for="userPwd" class="sr-only">密码</label>
    <input type="password" id="userPwd1" name="password2" style="margin-top:15px" class="form-control" placeholder="请确认密码" required autocomplete="off" maxlength="18">
    <a href=""><button class="btn btn-lg btn-primary btn-block" type="submit" id="signinSubmit">注册</button></a>
    <p style="color:red;font-size:20px">{{ msg }}</p>
  </form>
  <!--<div class="footer">-->
    <!--&lt;!&ndash;<p><a href="index.html" data-toggle="tooltip" data-placement="left" title="不知道自己在哪?">回到后台 →</a></p>&ndash;&gt;-->
  <!--</div>-->
</div>
{% endblock %}
{% block js2 %}
{{ block.super }}
<script src="/static/js/bootstrap.min.js"></script>
<script>
$('[data-toggle="tooltip"]').tooltip();
window.oncontextmenu = function(){
	//return false;
};
$('.siteIcon img').click(function(){
	window.location.reload();
});
$('#signinSubmit').click(function(){
	if($('#userName').val() === ''){
		$(this).text('用户名不能为空');
	}else if($('#userPwd').val() === ''){
		$(this).text('密码不能为空');
	}else{
		$(this).text('请稍后...');
	}
});
</script>
{% endblock %}